export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_COUNT_PRODUCTS = "GET_COUNT_PRODUCTS";
export const GET_COUNT_PRODUCTS_SUCCESS = "GET_COUNT_PRODUCTS_SUCCESS";
export const GET_COUNT_PRODUCTS_ERROR = "GET_COUNT_PRODUCTS_ERROR";
