export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USERS_BY_ID = "GET_USERS_BY_ID";
export const GET_USERS_BY_ID_SUCCESS = "GET_USERS_BY_ID_SUCCESS";
export const GET_USERS_BY_ID_ERROR = "GET_USERS_BY_ID_ERROR";

export const GET_POSTS_BY_ID = "GET_POSTS_BY_ID";
export const GET_POSTS_BY_ID_SUCCESS = "GET_POSTS_BY_ID_SUCCESS";
export const GET_POSTS_BY_ID_ERROR = "GET_POSTS_BY_ID_ERROR";

export const GET_ALBUMS_BY_ID = "GET_ALBUMS_BY_ID";
export const GET_ALBUMS_BY_ID_SUCCESS = "GET_ALBUMS_BY_ID_SUCCESS";
export const GET_ALBUMS_BY_ID_ERROR = "GET_ALBUMS_BY_ID_ERROR";

export const PUT_USERS_BY_ID = "PUT_USERS_BY_ID";
export const PUT_USERS_BY_ID_SUCCESS = "PUT_USERS_BY_ID_SUCCESS";
export const PUT_USERS_BY_ID_ERROR = "PUT_USERS_BY_ID_ERROR";
 
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const BUTTON_MENU = "BUTTON_MENU";